apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot
  labels:
    app: bot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bot
  template:
    metadata:
      labels:
        app: bot
    spec:
      containers:
      - name: bot-app
        image: mallik2001/bot:tag
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: bot-service
spec:
  selector:
    app: bot
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer

